ClusterLabs/sbd

agent/sbd, man/sbd.8.pod, src/sbd-cluster.c, src/sbd-common.c, src/sbd-inquisitor.c, src/sbd-md.c, src/sbd-pacemaker.c, src/sbd.h, src/sbd.sh, src/setproctitle.c, tests/regressions.sh
See  	7090581 commit message for details.
An analogy to this at the booth side:
- https://github.com/ClusterLabs/booth/pull/23
- https://github.com/ClusterLabs/booth/pull/24
=> Fix license notices

src/sbd.sysconfig
According to the documentation and the comment in the sysconfig file,
the default for SBD_STARTMODE should be "always".
The other option here is to update the documentation to document
"clean" as the default. If you'd prefer that, I can flip this patch - though 
I think retaining the defaults is the less surprising choice.
=> Set SBD_STARTMODE to "always" by default

man/sbd.8.pod, src/sbd-cluster.c, src/sbd-inquisitor.c
Adds a paragraph about disk-less mode to the man page, as well as fixing some minor typos and trailing whitespace.
=> Update the man page and fix some minor typos

Makefile.am
If user run "make rpm" without running "make srpm",
it will report error that tarball does not exist, that
is because the commit in spec does not change.
=> fixed:Makefile.am:substitute commit in sbd.spec when running "make rpm"

src/sbd-common.c
Within set_servant_health cl_log is called with a string variable and no
parameters. This leads to compiler errors when building with --Wformat
--Werror=format-security.
Introduce a dummy format string ("%s") to suppress this error.
=> build: fix error when compiling with format-security

man/sbd.8.pod, src/sbd.sysconfig
This patch removes the vestigial SBD_WATCHDOG option completely.
The watchdog is enabled by default and configured to use /dev/watchdog.
By passing /dev/null as the watchdog device, use of the watchdog can
be disabled.
Update the documentation to reflect this change.
=> Clarify documentation around watchdog option (-W)

src/sbd-common.c
Don't know what led to having the reboot there unconditionally.
But like this you get a shutoff if you request one.
And as for some hardware-watchdogs you can configure them
to shutoff instead of reboot it might be interesting to have the
equivalent there.
=> Fix: Don't reboot if off is requested

src/sbd-common.c, src/sbd-inquisitor.c, src/sbd-md.c, src/sbd.h
As stated in the fix-commit:
If disk-servant does a sysrq-reset sbd-inquisitor has to
terminate so that the watchdog can supervise the sysrq-execution.
Otherwise it goes into a respawn-loop on sysrq-reset failing.
Till now inquisitor received an RT-Signal (sbd-custom name SIG_IO_FAIL) prior to disk-servant-child's SIGCHLD.
Disabled sending the SIG_IO_FAIL in cases where the disk-servant wants to trigger a reset (fenced by another node writing the reset-message to the message-slot on the shared disk).
Whenever now a SIGCHILD is received from a disk-servant-process without a SIG_IO_FAIL before it is assumed that a reset was requested and inquisitor exits without gracefully closing the watchdog so that whatever the disk-servant has triggered (sysrq) is observed by the hardware-watchdog. …
=> Fix reboot req on sysrq not working

configure.ac, src/sbd-cluster.c
Quick and simple approach for tackling the issue that sbd won't suicide when loosing disk & 2nd node on a 2Node cluster.
=> Fix: cluster-servant: check for corosync 2Node mode

.travis.yml, tests/regressions.sh
Obviously udev doesn't trigger creation of files under /dev/mapper
inside privileged docker container - do it manually.
Make regressions.sh exit with an error-code to make it easier
for travis.
=> travis: add regressions.sh

src/sbd-common.c, src/sbd-inquisitor.c, src/sbd.h
refactored watchdog functions to be based on parameters instead of global config
todo: watchdog-drivers missing /sys/dev/char/10:130/device/driver don't show a proper driver
Some output examples:
```
>> sbd query-watchdog
Discovered 5 watchdog devices:
[1] /dev/watchdog1
Identity: iTCO_wdt
Driver: iTCO_wdt
[2] /dev/watchdog2
Identity: Software Watchdog
Driver: softdog
CAUTION: Not recommended for use with sbd.
[3] /dev/watchdog
Identity: iamt_wdt
Driver: mei_wdt
[4] /dev/watchdog0
Identity: iamt_wdt
Driver: mei_wdt
[5] /dev/watchdog_link
Identity: iamt_wdt
Driver: mei_wdt
>> sbd -w /dev/watchdog test-watchdog
WARNING: This operation is expected to force-reboot this system
without following any shutdown procedures.
Proceed? [NO/Proceed] Proceed
Initializing /dev/watchdog with a reset …
```
=> Add commands to test/query watchdogs

src/sbd-common.c
Increase buffer size to fix the following error when building using gcc 7.2.1 on Debian:
```
gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/include/pacemaker -I/usr/include/heartbeat -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time -D_FORTIFY_SOURCE=2 -Werror -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pacemaker  -I/usr/include/libxml2  -D_GNU_SOURCE -DCHECK_AIS -DSBINDIR=\"/usr/sbin\" -g -O2 -fdebug-prefix-map=/home/vvidic/work/scm/debian-ha/sbd=. -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/x86_64-linux-gnu/pacemaker -c -o sbd-md.o sbd-md.c
sbd-common.c: In function ‘watchdog_populate_list’:
sbd-common.c:249:28: error: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of …
```
=> Fix: gcc format string error

src/sbd-common.c
Add include for makedev, major and minor.
```
sbd-common.c:268:13: error: In the GNU C Library, "makedev" is defined
by <sys/sysmacros.h>. For historical compatibility, it is
currently defined by <sys/types.h> as well, but we plan to
remove this soon. To use "makedev", include <sys/sysmacros.h>
directly. If you did not intend to use a system-defined macro
"makedev", you should undefine it after including <sys/types.h>. [-Werror]
{makedev(10,130), 0};
```
=> Fix: build error with glibc 2.25

configure.ac, src/sbd-cluster.c
Pacemaker-2.0 removed support for corosync 1 cluster layer:
https://github.com/ClusterLabs/pacemaker/commit/7a9891f29
=> Build: cluster-servant: Compile with pacemaker-2.0

src/sbd.service.in, src/sbd.sysconfig, src/sbd_remote.service.in
Fixes the issue we recently discussed on the clusterlabs-list that sbd failing to start didn't prevent pacemaker from coming up.
This is kind of severe as pacemaker would run without supervision by sbd, watchdog would possibly not be armed and the poison-pill wouldn't be read from the storage.
What led to this finding was systemd timing out on trying to start sbd when SBD_DELAY_START is enabled and msgwait > default startup-timeout.
Thus I added some reminder to check for the timeout to sbd.sysconfig.
In the code - right before enabling the watchdog it says:
```
/* We only do this at the point either the disk or
* cluster servants become healthy
*/
```
In case of having no disks configured this would mean that my patch would create a deadlock.
But fortunately this comment seems to be a …
=> Startup issues

src/sbd-md.c
dump_headers() should return non-zero if open_device got failure.
=> sbd-md: dump_headers returns 0 even open_device failed

src/sbd-cluster.c, src/sbd-common.c, src/sbd-inquisitor.c, src/sbd-md.c, src/sbd-pacemaker.c
With the refactoring of logging parts and 1ee3503, sbd became too
silent given the default logging level LOG_WARNING, even under the
situations where it's supposed to tell something.
This commit changes sbd's default logging level to LOG_NOTICE.
Meanwhile pacemaker library's logging level remains at LOG_WARNING.
With "-v", sbd's logging level is set to LOG_INFO.
With "-vv", sbd's logging level is set to LOG_DEBUG.
With "-vvv", both sbd's and pacemaker library's logging levels are set
to LOG_DEBUG.
It also upgrades important messages and downgrades unimportant ones.
=> Log: change sbd's default logging level to LOG_NOTICE

src/sbd-md.c
Based on the patch from Lidong Zhong <lidong.zhong@suse.com>
With this change, when using the lha stonith agent
"stonith:external/sbd", stonith resource will report errors rather than
be quiet if any sbd devices failed, so that users can realize. And it
won't trigger deregistration of the fencing device from
pacemaker-fenced, which makes sense -- We should try hard to use a
fencing device if there's any chance. If it really doesn't work,
it'll fail to fence then.
The issue was originally brought up from:
https://github.com/ClusterLabs/sbd/pull/40#issuecomment-353266808
Another possible solution of considering to return positive if a quorate
number of devices can be listed properly was suggested.
However so far all the "command" functions consistently return -1 when
failed, and then sbd …
=> Fix: sbd-md: return error if faied to list any devices

.travis.yml
Using mock on top of a simple fedora-28 instead of the alectolytic/rpmbuilder-images makes the build run in a more restricted environment and it is more like the official way of building fedora/centos.
Obviously it doesn't require the matching alectolytic/rpmbuilder-image to be available.
Downside is that it takes roughly double resources (build + regression-test) compared to using alectolytic/rpmbuilder.
Alternative thing to investigate might be using mock directly on top of the travis-ubuntu-container.
=> travis: use mock on top of plain fedora-28 as build-host

src/sbd-inquisitor.c, src/sbd.sysconfig
SBD_DELAY_START now can also be enabled by being set to a specific delay
value, in seconds. Sometimes a longer delay than the default, "msgwait",
is needed, for example in the cases where it's considered to be safer to
wait longer than:
corosync token timeout + consensus timeout + pcmk_delay_max + msgwait
Be aware that the special value "1" means "yes" rather than "1s".
This addresses the issue brought up from https://github.com/ClusterLabs/sbd/pull/56.
=> Feature: sbd-inquisitor: SBD_DELAY_START can be configured with a delay value

configure.ac, src/sbd-pacemaker.c
For backward compatibility add some compatibility code
for if pe_new_working_set isn't available.
=> Refactor: use pacemaker's new pe api with constructors/destructors

src/sbd-inquisitor.c, src/sbd-md.c, src/sbd.h
fixes as well potential NULL pointer passing to log automatically detected by GCC9
=> Refactor: fail earlier on empty diskname

src/sbd-inquisitor.c, src/sbd-md.c, src/sbd-pacemaker.c, src/sbd.h
Exit pcmk-servant on graceful pacemaker shutdown and go back
to state before pacemaker was detected initially.
Purge all cib-traces otherwise and try to reconnect within timeout.
The up-to-now-solution seems to be working more or less accidentially.
Especially since pacemaker-2.x a graceful shutdown of pacemaker leaving sbd & corosync alive quite often leads to a watchdog-reboot.
This approach is watching the cib and if the connection goes away after shutdown-state has been seen and subsequently all resources on the node are down it assumes a graceful pacemaker-shutdown.
On top the various timeouts are set to more reasonable values.
Effect should be both more reliable detection of graceful pacemaker shutdown (+ subsequent survival of the node) and enforced properly timeout-observed …
=> Fix: sbd-pacemaker: make handling of cib-connection loss more robust

src/sbd-pacemaker.c
Prevents possible subsequent null-pointer access and avoids
unnecessary search for node.
=> Fix: sbd-pacemaker: bail out of status earlier

src/sbd-inquisitor.c
Previously with a monitor configured for sbd resource, the messages would
be flooding logs.
Probably the message doesn't necessarily belong to a notice, but in any
case it makes sense only for watch mode.
It's also rephrased a little since users were scared while seeing "...
writing 'b to sysrq ..." :-)
=> Fix: sbd-inquisitor: Avoid flooding logs with messages that hint the default/configured timeout action

src/sbd-common.c, src/sbd-inquisitor.c, src/sbd.h, src/sbd.sysconfig
```
#
#
SBD_MOVE_TO_ROOT_CGROUP=auto
```
Possible additions would be adding a way to define the name of the
slice to switch to instead of root-slice.
In auto-mode it might be interesting as well to define a minimum rt-budget
that prevents switching to root-slice (atm it is anything > 0).
=> Fix: sbd-common: query rt-budget > 0 otherwise try moving to root-slice

configure.ac, src/sbd-cluster.c
using votequorum_getinfo.
To have at least basic liveness-observation of the corosync daemon without
much dependencies to the rest of the code.
As this is all just done on the local node we can easily switch to using the
cpg-protocol pacemaker is already using once we have a solution for automatically
derived timout-setting as being addressed in
#76 
There is as well still demand for simplified / robustified handling of all the
connections the cluster-watcher meanwhile has to corosync (cpg, cmap, votequorum).
These issues are addressed in #81 #80.
Maybe this can be postponed till we have a way to tell if corosync-disconnection
was done gracefully triggered by e.g. systemd. In case of a non-graceful-disconneciton
we would assume that pacemaker has lost corosync-connection as well so that …
=> Fix: sbd-cluster: periodically check corosync-daemon liveness

.gitignore, .travis.yml, Makefile.am, configure.ac, man/Makefile.am, sbd.spec, src/Makefile.am, tests/regressions.sh
- Update .gitignore
- Make tar generation smarter
- check for git underneath
- check for git modifications
- build proper tar without git
- Versioned sbd.spec goes to subdir
- Specify additional source-files for distcheck to find
- Add tests/regressions.sh to check-target
- Add env SBD_BINARY to use custom binary in regression.sh
- Use srpm-target directly from ubuntu for travis
=> Update build/test for more CI-friendliness

.travis.yml, src/sbd-cluster.c, src/sbd-pacemaker.c
and add fedora-rawhide that was as of now the first fedora to build-fail because of using them.
and unfortunately fedora-rawhide seems to have issues gpg-keys
doing an update without gpg-key-checking and removing the gpg-check from mock-config for rawhide seems to solve the issue for now and should be removed once the issue is gone otherwise.
=> avoid deprecated naems for g_main-loop-functions

Makefile.am, tests/regressions.sh
Unfortunately exclude-patterns require git > 1.9 so go with
a little fiddling but compatible to older git versions.
=> Fix: build: don't fail export-target with uncommitted .travis.yml

.travis.yml, Makefile.am, autogen.sh, configure.ac, man/sbd.8.pod, sbd.spec, src/Makefile.am, src/sbd-common.c, src/sbd-inquisitor.c, tests/Makefile.am, tests/configure.ac, tests/regressions.sh, tests/sbd-testbed.c
This basically adds a preload-library for sbd that can be used as a testbed to write regression-tests for sbd in daemon-mode. (instead of actually rebooting a log is created that can be used to verify if sbd would have triggered a reboot when it should have)
regressions.sh is added a couple of tests that make use of these new possibilities.
The preload-library adds a virtual-watchdog-device (all in userspace),
interception for access to the block-devices so that plain-files can be used
and interception of reboot & sysrq-trigger to prevent actual reboots.
In addition it is possible to as well intercept and map to read/write/seek
asynchronous-IO for platforms that don't support the corresponding
systemcalls (userspace-qemu to emulate certain foreign-architectures).
regressions.sh & the …
=> Daemon tests

.travis.yml, tests/regressions.sh
This adds both additional architectures (aarch64 & s390x) and Suse build-targets to the travis-CI.
While adding the Suse build-targets just introduced a bit of uglyness due to longer lines and
less readability due to the different naming conventions for mock-build-targets and containers
the additional architectures were a real pain due to them running in LXD containers.
Problem is that the containers inside thes LXD containers can't be run privileged and not
even sys_admin-capabilities do arrive properly inside the container.
For testing the packages this can be mitigated instructing the new testbed-preload-library
to remove the requirement for device-mapper (buying us a slightly inferior test but well ...).
The real pain was mock that had to be instructed not to do a couple of things …
=> travis: add aarch64 s390x epel-8

.travis.yml
Unfortunately ppc64le-containers on travis don't seem to be able
to cope with the default timeout accessing repos of 30s.
Raising that to 300s with some ugly hackery seems to solve
the issue.
=> travis: switch to fedora 31 as build-host

agent/sbd.in
String comparison should use `=` instead of `-eq`.
=> Fix: agent: correctly compare string values when calculating timeout

.gitignore, Makefile.am, README.md, man/Makefile.am, man/sbd.8.pod.in, src/sbd.sysconfig
Environment section is auto-generated from sbd.sysconfig.
Originally intended to have this done by config.status - thus the @...@ an .in extension - but finally went for a simple sed replace.
Intention is to still have documentation for environment-variables even if some high-level-tool (e.g. pcs) overwrites /etc/sysconfig/sbd or config-files are copied around.
=> Doc: add environment section to man-page

configure.ac, src/sbd-pacemaker.c
Pacemaker introduced a new no-quorum-policy no_quorum_demote.
Code up to now would probably not compile against new pacemaker-headers (dependent on
compiler and flags) or static analysis would catch not all enums being handled.
Even worse is with using existing sbd-binaries (or compiled in an environment that doesn't
complain) a loss of quorum would be ignored by sbd possibly leading to split-brain.
Now we test for existence of the new enum value and use it (same as no_quorum_stop).
To be more robust against no-quorum-policies added in the future unknown policies are
now handled as would be done with no_quorum_suicide. This triggers an immediate
suicide in case of quorum-loss and unknown policy which should provide best robustness
against split-brain.
=> handle new no_quorum_demote introduced in pacemaker

.travis.yml, configure.ac, src/sbd-cluster.c
If qdevice is used and sync_timeout is higher than watchdog-timeout then
we can't be sure that quorum-state is updated quick enough so that
it can be used to trigger a suicide reliably quick.
Thus it is advisable to prevent startup of resources in such a case
(as we are doing when pacemaker finds stonith-watchdog-timeout
too small for the watchdog-timeout set in sbd). This can easily
be achieved by delaying sbd-startup (finally systemd will make
an end to it after the startup-timeout configured with the unit)
till the timing-requirements are fulfilled. While in the sbd-startup-delay
phase the admin can still correct qdevice timing.
When qdevice is enabled during operation or timing is modified
this is checked via cmap-tracking of quorum.device.mode &
quorum.device.sync_timeout.
Of course …
=> Fix: sbd-cluster: match qdevice-sync_timeout against wd-timeout

configure.ac, src/sbd-inquisitor.c, src/sbd-pacemaker.c, src/sbd.h, src/sbd.sysconfig
State query ping of pacemakerd prevents pacemakerd from
starting any sub-daemons (and thus services) if sbd can't
reach it via ipc. As a health-check get timestamp from
pacemakerd. On shudown fetch info about graceful
shutdown from pacemakerd.
Use new pacemakerd-api provided by pacemaker.
This refactors #106 sync with pacemakerd
to use new pacemakerd-api in pacemaker based on
generic client api framework.
Added SBD_SYNC_RESOURCE_STARTUP defaulting to 'no' so
that upgrading pacemaker without sbd doesn't lead to pacemaker
locked waiting to be pinged by sbd.
=> Fix: sbd-pacemaker: sync with pacemakerd for robustness

src/sbd-inquisitor.c
Due to the change of https://github.com/ClusterLabs/sbd/commit/f4d38a073ce3bfa2078792f1cc85229457430292, a warning is output to syslog when the sbd command is executed, which confuses users.
```
Red Hat Enterprise Linux release 8.3 (Ootpa)
sbd-1.4.1-7.el8.x86_64
SBD_SYNC_RESOURCE_STARTUP=yes
(1)
Discovered 2 watchdog devices:
[1] /dev/watchdog
Identity: i6300ESB timer
Driver: <unknown>
[2] /dev/watchdog0
Identity: i6300ESB timer
Driver: <unknown>
Dec 11 12:02:25 rhel83-1 <daemon.warning> sbd[1846233]: warning: main: SBD built against pacemaker supporting pacemakerd-API. Should think about enabling SBD_SYNC_RESOURCE_STARTUP.
(2)
sosreport (version 3.9)
:
Starting 76/119 pacemaker       [Running: insights networking networkmanager pacemaker]  *1
:
Dec 11 12:21:04 rhel83-2 <daemon.warning> …
```
=> Fix: sbd-inquisitor: check SBD_SYNC_RESOURCE_STARTUP only in watch mode

src/sbd.sysconfig.in
now that the default is configurable at compile-time
=> Doc: adapt description of startup/shutdown sync with pacemaker

src/sbd-inquisitor.c
It was introduced by cc46bb4. References of `argv[optind]` should be
after the check of `optind` against `argc`.
=> Fix: sbd-inquisitor: prevent segfault if no command is supplied

src/sbd-inquisitor.c
Prior to 6c1c641, options used to be set in sbd.sysconfig template with
empty strings like:
```
SBD_PACEMAKER=
```
With invocations of sbd.sh by sbd.service, the defaults would be taken
with calls like:
```
: ${SBD_PACEMAKER:="true"}
```
But with that commit, for some of the options, either wrong values are
taken or parsing errors occur. This might break existing setups that get
upgraded with an old sysconfig.
=> Fix: sbd-inquisitor: take the defaults for the options set in sysconfig with empty strings

src/sbd-inquisitor.c
Somehow an user's own monitoring agent doesn't well parse an SBD_DEVICE
setting with spaces between the device names:
`SBD_DEVICE="/dev/<a>; /dev/<b>; /dev/<c>"`
And eventually it calls an sbd command:
`sbd list -d " /dev/<b>"`
--  A space is prefixed to the device name which is quoted.
Of course it could be easily fixed in the setting or their agent. But
OTOH, sbd'd better tolerate and strip any leading spaces of command line
option values.
=> Fix: sbd-inquisitor: tolerate and strip any leading spaces of command line option values

src/sbd-inquisitor.c
SBD sysconfig option `SBD_DELAY_START` is for addressing the case where cluster nodes reboot so fast even before fencing targeting it returns.
This could be common for virtual machines.
So far technically, a setting `SBD_DELAY_START=yes` takes effect only for sbd with shared disk, since the delay value is basically `msgwait` retrieved from sbd metadata.
For diskless sbd, for now we'd have to specify `SBD_DELAY_START` with a explicit delay value.
We need to implement to make `SBD_DELAY_START=yes` take effect for diskless sbd as well. In this case, the delay value should be `SBD_WATCHDOG_TIMEOUT * 2`
=> Fix: sbd-inquisitor: Implement default delay start for diskless sbd

src/sbd-md.c, src/sbd.h, tests/sbd-testbed.c
switch to using a single aligned buffer that stays allocated.
- free to use allocation mechanism that doesn't allow to
use free() to hand back (not needed for current posix_memalign)
- avoid memory fragmentation risk (and thus risk to run out of
hogged memory) due to frequent alloc/free of aligned memory
Switching from ```forking``` to ```simple``` should probably be
thought over again as sbd is doing quite some checks that
should be done before systemd should assume sbd as started
and thus start pacemaker.
Nothing severe should happen though since we have startup-
synchronization between the daemons meanwhile.
To leave legacy ```forking``` startup behind and still have the
behavior that pacemaker is just started by systemd when sbd
has checked config, watchdog-device & disks ```notify``` …
=> [WIP] Fix: avoid using deprecated valloc & frequent aligned alloc

configure.ac, sbd.spec
```
Changes since 1.5.0:
- improve/fix cmdline handling
- tell the actual watchdog device specified with -w
- tolerate and strip any leading spaces of commandline option values
- Sanitize numeric arguments
- if start-delay enabled, not explicitly given and msgwait can't be
read from disk (diskless) use 2 * watchdog-timeout
- avoid using deprecated valloc for disk-io-buffers
- avoid frequent alloc/free of aligned buffers to prevent fragmentation
- fix memory-leak in one-time-allocations of sector-buffers
- fix AIO-API usage: properly destroy io-context
- improve/fix build environment
- validate configure options for paths
- remove unneeded complexity of configure.ac hierarchy
- correctly derive package version from git (regression since 1.5.0)
- make runstatedir configurable and derive …
```
=> Bump Version to 1.5.1

Makefile.am, tests/regressions.sh
- have image-files in /dev/shm to assure they are in memory and
sbd opening the files with O_SYNC doesn't trigger unnecessary
syncs on a heavily loaded test-machine
- wrapping away libaio and usage of device-mapper for block-device
simulation can now be passed into make via
SBD_USE_DM & SBD_TRANSLATE_AIO
- have variables that configure test-environment be printed
out prior to running tests
=> test: a few tweaks regarding setup of test-environment

src/sbd-md.c
in slot_list instead of jumping to the common out-code.
Using the common out-code should just add 3x free(NULL)
but gcc-12 dynamic-memory static analysis does complain.
The code doesn't get that more ugly so let's do gcc the
favor for now.
This is the patch for doing the early return:
```
@@ -573,7 +573,7 @@ slot_list(struct sbd_context *st)
s_header = header_get(st);
if (!s_header) {
rc = -1; goto out;
return -1;
}
s_node = sector_alloc();
```
Strange is that changing the order of the cleanup-code
seems to satisfy gcc as well.
Doing the de-allocation in reverse order compared to 
allocation might be a bit cleaner but shouldn't have any
influence here.
So let's rather go with that.
=> Refactor strange dynamic-allocation-finding of gcc-12

sbd.spec
Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>
=> rpm: use new package name for pacemaker devel on opensuse

sbd.spec
opensuse 15 still uses the old package name, while tumbleweed the new
one
Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>
=> rpm: use new package name for pacemaker devel on opensuse (take 2)

src/sbd-common.c
Both when running as daemon and with 'test/query-watchdog'
Looks a bit more than it actually is as indentation of functions
with heavier edit was moved from tabs to spaces.
Maybe that should have gone into a separate commit ...
Still hoping that the tabs indentation will age out over time ;-)
```
[root@node2 ~]# sbd test-watchdog -w /dev/watchdog
WARNING: This operation is expected to force-reboot this system
without following any shutdown procedures.
Proceed? [NO/Proceed] Proceed
Initializing /dev/watchdog with a reset countdown of 5 seconds ...
Failed to initialize watchdog!!!
Discovered 2 watchdog devices:
[1] /dev/watchdog
Identity: Busy: PID 21850 (sbd)
Driver: <unknown>
[2] /dev/watchdog0
Identity: Error: device hogged via alias major/minor?
Driver: <unknown>
```
=> Fix: Be a bit more descriptive on issues opening watchdog-devices

src/sbd-inquisitor.c
And tell user to fix the configuration by either enabling SBD_PACEMAKER
or explicitly disabling SBD_SYNC_RESOURCE_STARTUP. Otherwise startup of
pacemaker would be hanging forever, since pacemaker only knows about
SBD_SYNC_RESOURCE_STARTUP.
AFAICS this is so far the best we can do to prevent cluster services from running into never ending startup, not to mention cluster services could not even be shut down under the situation.
This is to address the topic brought up from:
https://github.com/ClusterLabs/pacemaker/pull/2119#discussion_r997274821
I realized this more or less matches the ideas brought up by the other PR:
https://github.com/ClusterLabs/sbd/pull/141
=> Fix: sbd-inquisitor: fail startup if pacemaker integration is disabled while SBD_SYNC_RESOURCE_STARTUP is conflicting

configure.ac, sbd.spec
```
Changes since 1.5.1:
- fail startup if pacemaker integration is disabled while SBD_SYNC_RESOURCE_STARTUP is conflicting (+ hint to overcome)
- improve logs
- when logging state of SBD_PACEMAKER tell it is just that as this might still be overridden via cmdline options
- log a warning if SBD_PACEMAKER is overridden by -P or -PP option
- do not warn about startup syncing with pacemaker integration disabled
- when watchdog-device is busy give a hint on who is hogging it
- improve build environment
- have --with-runstatedir overrule --runstatedir
- use new package name for pacemaker devel on opensuse
- make config location configurable for man-page-creation
- reverse alloc/de-alloc order to make gcc-12 static analysis happy
- improve test environment
- have image-files in /dev/shm to …
```
=> Bump Version to 1.5.2

tests/sbd-testbed.c
as that is rather what sbd would link against without preloading on distros linking different library versions under these 2 names
=> test: load libaio.so instead of libaio.so.1

src/sbd-inquisitor.c
... to prevent the unnecessary call to crm_get_msec() and the warning about an invalid value.
This addresses the issue brought up from:
https://github.com/ClusterLabs/pacemaker/pull/3643#pullrequestreview-2448716154
=> Fix: sbd-inquisitor: avoid parsing SBD_DELAY_START as a time duration if its value is boolean false

sbd.spec, tests/sbd-testbed.c
... i.e. the one with the major version number such as libaio.so.1, to
likely avoid requiring libaio-devel for the generic symbolic link
libaio.so.
This is achieved by adding the ability to specify a libaio name
with -DLIBAIO_NAME via CFLAGS.
This also ensures that the corresponding library name is shown in case
of dlopen() error together with more detail from dlerror()
=> Build: spec: try finding and using libaio.so.x library name

.gitignore, src/sbd-cluster.c
cleanup header import including <crm/crm.h> directly in sbd-cluster.c.
And ignore CLAUDE.md - as otherwise build is failing when it sees an untracked file.
=> cleanup header import
